<?php
/**
 * @file
 * test.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function twitter_autopost_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-page-field_twitter_autopost'
  $field_instances['node-page-field_twitter_autopost'] = array(
    'bundle' => 'page',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'fences_wrapper' => 'div',
    'field_name' => 'field_twitter_autopost',
    'label' => 'Auto Post to Twitter',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 32,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Auto Post to Twitter');

  return $field_instances;
}
