<?php

/**
 * Implements hook_menu().
 */
function twitter_autopost_menu() {
  $items['admin/config/services/twitter-autopost-node-settings'] = array(
    'title' => 'Twitter Auto-Post',
    'type' =>  MENU_NORMAL_ITEM,
    'description' => "Twitter Auto post settings",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twitter_autopost_admin_node_settings_form'),
    'file' => 'twitter_autopost.pages.inc',
    'access arguments' => array('administer twitter autopost'),
  );
  $items['admin/config/services/twitter-autopost'] = array(
    'title' => 'Twitter Auto-Post',
    'type' =>  MENU_NORMAL_ITEM,
    'description' => "Twitter Auto post settings",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twitter_autopost_admin_account_form'),
    'file' => 'twitter_autopost.pages.inc',
    'access arguments' => array('administer twitter autopost'),
  );
  $items['admin/config/services/twitter-autopost-add'] = array(
    'title' => 'Twitter Auto-Post Add Account',
    'type' =>  MENU_NORMAL_ITEM,
    'description' => "Twitter Auto post settings",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('twitter_autopost_admin_settings_form'),
    'file' => 'twitter_autopost.pages.inc',
    'access arguments' => array('administer twitter autopost'),
  );
  return $items;
}

/**
 * Implements hook_node_insert().
 */
function twitter_autopost_node_insert($node) {
  post_to_twitter($node);
}

/**
 * Implements hook_node_update().
 */
function twitter_autopost_node_update($node) {
  post_to_twitter($node);
}

/**
 * Implements hook_permission().
 */
function twitter_autopost_permission() {
  $perm = array(
    'administer twitter autopost' => array(
      'title' => t('Administer Twitter Autopost'),
    ),
  );
  return $perm;
}

/**
 * Implements hook_form_alter().
 */
function twitter_autopost_form_alter(&$form, &$form_state, $form_id) {
  $node_types = node_type_autopost();
  twitter_autopost_accounts();
  if (in_array($form['type']['#value'], $node_types)) {
    $form['twitter_autopost'] = array(
      '#title' => t('Post this content on twitter'),
      '#type' => 'checkbox',
      '#description' => t("Slect this to post to twitter account"),
    );
    $accounts = twitter_autopost_accounts();
    $screen_names = array();
    foreach ($accounts as $account) {
      if ($account->is_default) {
        array_unshift($screen_names, 'Default: (@' . $account->screen_name . ')');
      }
      else {
        array_push($screen_names, '@' . $account->screen_name);
      }
    }
    $form['twitter_autopost_account'] = array(
      '#title' => t('Which Twitter Account to use?'),
      '#type' => 'select',
      '#options' => $screen_names,
    );
  }
}

/**
 * Posts node tweet text to twitter account
 *
 * @param Object $node
 *
 */
function post_to_twitter($node) {
  // Needs to be refactored to the new logic

  //See if the content should be auto posted
  if ($node->field_twitter_autopost[LANGUAGE_NONE][0]['value'] == 1) {
    $twitter_account = "";
    $result = db_query('SELECT twitter_uid FROM twitter_account');
    foreach ($result as $account) {
      $twitter_account = twitter_account_load($account->twitter_uid);
    }
    try {
      $message = '';
      $uri = entity_uri('node', $node);
      $node_url = $GLOBALS['base_url'] . '/' . url($uri['path']);
      $tiny_url = twitter_shorten_url($node_url);
      // Using text here because it is already shortened to 140
      $node_tweet_title = $node->field_tweetbutton[LANGUAGE_NONE][0]['text'];
      // Check in case tiny url and node title together are longer than 140
      if ((strlen($node_tweet_title) + strlen($tiny_url)) <= 140) {
        $message = $node_tweet_title . " " . $tiny_url;
      }
      else {
        // If they are calculate how much has to be removed from title text
        $message_length_together = strlen($node_tweet_title) + strlen($tiny_url);
        $amount_to_take_off = $message_length_together - 140;
        $message = substr($node_tweet_title, 0, strlen($node_tweet_title) - $amount_to_take_off) . " " . $tiny_url;
      }
      twitter_set_status($mnn_twitter_account, $message);
      // Unchecking the post to twitter so on updates it wont post bad content
      db_update('field_data_field_post_to_twitter')
        ->expression('field_post_to_twitter_value', 0)
        ->condition('entity_id', $node->nid)
        ->execute();
      drupal_set_message(t('Successfully posted to Twitter'));
    }
    catch (TwitterException $e) {
      drupal_set_message(t('An error occurred when posting to Twitter: @message',
      array('@message' => $e->getMessage())), 'warning');
    }
  }
}

/**
 * Return an array of content types that are used in autopost.
 *
 */
function node_type_autopost() {
  $result = db_query('SELECT * FROM twitter_autopost_node_types WHERE use_autopost=1');
  $node_types_autopost = array();
  foreach ($result as $type) {
    array_push($node_types_autopost, $type->node_type);
  }
  return $node_types_autopost;
}

/**
 * Return an array of Twitter Accounts.
 *
 */
function twitter_autopost_accounts() {
  $result = db_query('SELECT screen_name, is_default FROM twitter_autopost_users');
  $twitter_autopost_accounts = array();
  foreach ($result as $account) {
     array_push($twitter_autopost_accounts, $account);
  }
  return $twitter_autopost_accounts;
}
